### ISSUE TITLE
numify_ver() is *not* how you do version comparisons

### ISSUE THREAD

**Issue by JohnPeacock** [miyagawa/cpanminus#574] opened 2018-06-01 01:17 UTC
See https://rt.cpan.org/Ticket/Display.html?id=125441 and https://github.com/chocolateboy/autobox/issues/13

You are violating the OO nature of version objects by trying to brew your own version comparisons and it's breaking other people's code.  This block is the problem:

```
sub build_stuff {
...
          my $action  = $local && !$reinstall
                      ? $self->numify_ver($version) < $self->numify_ver($local)
                          ? "downgraded"
                          : "upgraded"
                      : undef;
...
```
Just use version objects directly and stop trying to impose some sort of common "format", since it will break as soon as someone switches from floating point to dotted decimal (as autobox has).  If you really want to have an object method in your class, do this:

```
  sub version {
      my($self, $ver) = @_;
      return version->new($ver);
  }
...
          my $action  = $local && !$reinstall
                      ? $self->version($version) < $self->version($local)
                          ? "downgraded"
                          : "upgraded"
                      : undef;
```

But this works equally well:
```
          my $action  = $local && !$reinstall
                      ? version->new($version) < $local
                          ? "downgraded"
                          : "upgraded"
                      : undef;
```
since you don't need to convert both variables to version objects at all, just let the version comparison code overloading work.

**Comment by miyagawa** [comment] 2018-06-01 01:37
@JohnPeacock thanks for the report. 

Two things.

a) I do not disagree that we can directly compare version objects, `numify` method in version.pm is a well documented method that is expected to return the decimal form of the version, so using them to compare two versions should not be a problem either.

b) the error message cited in the ticket seems it's coming out of cpanfile version requirement, which I believe has nothing to do with the code you just quoted above. I just tried upgrading and downgrading autobox from 2 to 3 and there's no warnings/errors like the above.

```
> cpanm autobox
--> Working on autobox
Fetching http://www.cpan.org/authors/id/C/CH/CHOCOLATE/autobox-v3.0.1.tar.gz ... OK
Configuring autobox-v3.0.1 ... OK
Building and testing autobox-v3.0.1 ... OK
Successfully installed autobox-v3.0.1 (upgraded from 2.83)
> cpanm autobox@2.83
--> Working on autobox
Fetching http://backpan.perl.org/authors/id/C/CH/CHOCOLATE/autobox-2.83.tar.gz ... OK
Configuring autobox-2.83 ... OK
Building and testing autobox-2.83 ... OK
Successfully installed autobox-2.83 (downgraded from v3.0.1)
1 distribution installed
```

**Comment by miyagawa** [comment] 2018-06-01 01:41
I'm trying to reproduce this with the quoted cpanfile above, with no avail:

```
> perl -Mautobox\ 11
autobox version 11 required--this is only version 2.83.
BEGIN failed--compilation aborted.

> cat cpanfile        
requires 'autobox', '>= 2.86';

> cpanm --installdeps .
--> Working on .
Configuring /private/tmp/MIgBHLF22 ... OK
==> Found dependencies: autobox
--> Working on autobox
Fetching http://www.cpan.org/authors/id/C/CH/CHOCOLATE/autobox-v3.0.1.tar.gz ... OK
Configuring autobox-v3.0.1 ... OK
Building and testing autobox-v3.0.1 ... OK
Successfully installed autobox-v3.0.1 (upgraded from 2.83)
<== Installed dependencies for .. Finishing.
1 distribution installed

> cpanm -v
cpanm (App::cpanminus) 1.7044 on perl 5.022000 built for darwin-2level
```

**Comment by miyagawa** [comment] 2018-06-01 03:10
The error message: 
```
Argument "^C\0^A" isn't numeric in numeric ge (>=) at ...
```

suggests that it was `eval`ing the string `v3.0.1` and was trying to compare with the version requirement. None of the code I can see in cpanm and its dependencies seems to do with the versions i have. I would be curious to know what versions of perl, version.pm, cpanm (or Carton) that the original reporter had to see this issue.

**Comment by JohnPeacock** [comment] 2018-06-01 10:45
Yes, we need much more detail from the original reporter about what software they were using.  I just looked for the obvious place where your code was attempting to both numify and compare two versions.

However, I have to emphasize that ->numify() and ->normal() were expected to be used where you wanted to *display* a version, not to be used for comparison. There are complicated rules about how to parse a version string into a version object precisely because comparing version strings is fraught with complications.  If you are using version.pm, you should be using the override methods for all version comparisons, because that is what they are there for.  Don't try to Do Your Own Thing.  It *will* break in subtle ways, especially in the realm of dotted decimal vs floating point comparisons.  Among other things, by using eval() you are forcing these objects to be treated as numbers, which they aren't.  Versions are not numbers, since numbers can be subject to representational loss when converting from Base10 to Base2, whereas versions are fixed values.

**Comment by miyagawa** [comment] 2018-06-01 20:15
> Yes, we need much more detail from the original reporter about what software they were using. I just looked for the obvious place where your code was attempting to both numify and compare two versions.

Well, "it's breaking other people's code. This block is the problem:" is a very strong accusation if you "just looked for the obvious place", since i'm sure that's not the code that is causing the problem.

> However, I have to emphasize that ->numify() and ->normal() were expected to be used where you wanted to display a version, not to be used for comparison.

I get that part. `numify_ver` was made so that we can turn the version to actual decimal numbers because that's how MetaCPAN is storing the versions internally (chase them if you have issues with that). Using this to compare versions for upgrade/downgrade was accidental and not intentional.

**Comment by miyagawa** [comment] 2018-06-01 20:50
b7730ad52de48d5b5b86f065dcfe49c70a71f6d6 removes the code. Again, I do not believe this is the cause of the problem reported originally.

**Comment by miyagawa** [comment] 2018-06-01 22:43
Closing this since i have no evidence that this quoted code is causing the issue.  And that code has been now fixed anyway.

@DrHyde should chime in and possibly reopen it, once we get which piece of the code or software is causing that errors.

**Closed by miyagawa** 2018-06-01 22:43 UTC

**Comment by davidcantrelluk2** [comment] 2019-09-06 11:05
FWIW I can no longer replicate this either. And I apologise, I should have been explicit back when I opened this about versions.
