### ISSUE TITLE
feature request: log to build.log even in --verbose mode

### ISSUE THREAD

**Issue by karenetheridge** [miyagawa/cpanminus#494] opened 2016-04-22 11:37 UTC
Even if installing in --verbose mode, it is sitll helpful to have the full build output in build.log, e.g. for tools such as App-cpanminus-reporter. Would it be possible?

**Comment by karenetheridge** [comment] 2016-04-22 11:37
cc @garu

**Comment by miyagawa** [comment] 2016-04-22 15:33
Dupe of #253 

I tried once and it wasn't as easy as I wished.

**Comment by miyagawa** [comment] 2016-04-22 15:34
Also #350 :)

**Closed by miyagawa** 2016-04-22 15:33 UTC
