### ISSUE TITLE
cpanm can't install Bundle::CPAN on Centos 7

### ISSUE THREAD

**Issue by michael-stevens** [miyagawa/cpanminus#504] opened 2016-07-08 16:13 UTC
Hi,

I'm having trouble installing Bundle::CPAN on Centos 7.

setup:

redhat system perl, install perl-core, gcc

install cpanminus either from yum or via the website

run: cpanm Bundle::CPAN

Fails with some kind of circular dependency issue:

cpanm (App::cpanminus) 1.7042 on perl 5.016003 built for x86_64-linux-thread-multi
Work directory is /root/.cpanm/work/1467993879.30746
You have make /bin/make
You have LWP 6.05
You have /bin/tar: tar (GNU tar) 1.26
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
Searching Bundle::CPAN () on cpanmetadb ...
--> Working on Bundle::CPAN
Fetching http://www.cpan.org/authors/id/A/AN/ANDK/Bundle-CPAN-1.862.tar.gz
-> OK
Unpacking Bundle-CPAN-1.862.tar.gz
Entering Bundle-CPAN-1.862
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (6.68)
Configuring Bundle-CPAN-1.862
Running Makefile.PL
Checking if your kit is complete...
Looks good
Writing Makefile for Bundle::CPAN
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.68)
Checking if you have ExtUtils::MakeMaker  ... Yes (6.68)
Checking if you have Test::Harness  ... Yes (3.28)
Checking if you have ExtUtils::CBuilder  ... Yes (0.280206)
Checking if you have File::Temp  ... Yes (0.2301)
Checking if you have Test::More  ... Yes (1.302037)
Checking if you have Data::Dumper  ... Yes (2.145)
Checking if you have IO::Compress::Base  ... Yes (2.061)
Checking if you have Compress::Zlib  ... Yes (2.061)
Checking if you have IO::Zlib  ... Yes (1.10)
Checking if you have Archive::Tar  ... Yes (2.08)
Checking if you have Module::Build  ... Yes (0.4005)
Checking if you have File::Spec  ... Yes (3.40)
Checking if you have Digest::SHA  ... Yes (5.85)
Checking if you have File::HomeDir  ... Yes (1.00)
Checking if you have Archive::Zip  ... Yes (1.30)
Checking if you have Net::FTP  ... Yes (2.77)
Checking if you have Term::ReadKey  ... Yes (2.33)
Checking if you have Term::ReadLine::Perl  ... Yes (1.0303)
Checking if you have YAML  ... Yes (0.84)
Checking if you have Parse::CPAN::Meta  ... Yes (1.4404)
Checking if you have Text::Glob  ... Yes (0.09)
Checking if you have CPAN  ... Yes (1.9800)
Checking if you have File::Which  ... Yes (1.21)
Checking if you have YAML::Syck  ... Yes (1.29)
Checking if you have IO::Tty  ... Yes (1.12)
Checking if you have Expect  ... Yes (1.33)
Checking if you have YAML  ... Yes (0.84)
Checking if you have Bundle::CPAN  ... No
Checking if you have Module::Signature  ... Yes (0.73)
Checking if you have CPAN::Reporter  ... Yes (1.2018)
Checking if you have Kwalify  ... Yes (1.22)
==> Found dependencies: Bundle::CPAN
Already tried Bundle::CPAN. Skipping.
-> FAIL Installing the dependencies failed: Module 'Bundle::CPAN' is not installed
-> FAIL Bailing out the installation for Bundle-CPAN-1.862.

**Comment by miyagawa** [comment] 2016-07-08 16:14
putting the bug in Bundle::CPAN mentioning itself aside, it makes no sense for you to install CPAN.pm with cpanm.

**Comment by shadowcat-mst** [comment] 2016-07-08 16:22
Bundle::CPAN doesn't mention itself in the bundle section - my suspicion is cpanm is accidentally picking up the =head1 NAME section's mention of the package name and not realising it's not inside the CONTENTS section which is where dependencies should come from.

I did tell the user that it was a silly thing to do, but cpanminus should either have working bundle support, or explicitly bail out when it sees one. Almost but not quite working benefits nobody.

**Comment by shadowcat-mst** [comment] 2016-07-08 16:27
Aha, no! The problem is that the tarball contains TWO bundles, and Bundle::CPANxxl deps on Bundle::CPAN, but cpanminus doesn't understand it's only supposed to look at the bundle actually asked for, so it tries to treat both bundles' deps as a single thing.

So, yeah, cpanminus' support for bundles is still broken, but apparently in an even more obscure way than I expected because bundles are even weirder than I thought they were.

Yay.

**Comment by miyagawa** [comment] 2016-07-08 16:27
I suspect it is this line in CPANxxl.pm https://metacpan.org/source/ANDK/Bundle-CPAN-1.862/CPANxxl.pm#L28

**Comment by shadowcat-mst** [comment] 2016-07-08 16:30
Yes. Which file cpanminus shouldn't be parsing at all for a request for Bundle::CPAN

**Comment by miyagawa** [comment] 2016-07-08 16:31
lol, Andreas fixed a related bug in CPAN.pm pretty recently for himself!
https://github.com/andk/cpanpm/commit/a6879ac05579cce3b013fc975b1283d6c902c5ac

**Comment by shadowcat-mst** [comment] 2016-07-08 16:33
Bundles: roll SAN check before touching.

**Comment by miyagawa** [comment] 2016-07-08 16:40
Yeah, I _think_ CPAN.pm installs Bundle modules first, then lookup the module name (i.e. `Bundle::CPAN`) from `@INC` to scan the contents. Quite different from how currently cpanm works, which is handling it as an additional source of dependencies in addition to META files.

An easiest workaround is to do a heuristic match on the file path, because CPAN.pm bundle isn't even in `lib/Bundle/CPAN.pm` - it is `CPAN.pm` in a root directory of the dist

**Comment by shadowcat-mst** [comment] 2016-07-08 16:46
Yeah, or to parse out the =head1 NAME or the package line and then only take bundle deps from that?

**Comment by miyagawa** [comment] 2016-07-08 16:46
yeah that works too (and/or parse `package Bundle::CPAN` line, which is becoming close to a territory of Module::Metadata)

**Comment by shadowcat-mst** [comment] 2016-07-08 16:49
The only thing I'm actually sure of here is that I wish everything was a Task:: instead already ;)

**Comment by miyagawa** [comment] 2016-07-08 16:54
right :) 

should be fixed in 0739c5c

**Closed by miyagawa** 2016-07-08 16:54 UTC

**Comment by miyagawa** [comment] 2016-07-08 17:01
if you try to install Bundle::CPANxxl first, you'll still see the "Already tried" error, but that's pretty hard to solve at this moment - the fix above is to just handle the requested bundle name, not all `*.pm` files in a dist.
