### ISSUE TITLE
cpanminus generates bad install.json for XSLoader

### ISSUE THREAD

**Issue by mark-5** [miyagawa/cpanminus#513] opened 2016-08-14 21:36 UTC
When installing XSLoader with either local-lib option, cpanm generates an install.json with an empty provides section. This causes issues when Carmel tries to resolve the XSLoader artifact.

It appears that XSLoader's Makefile.PL is cleaning XSLoader.pm(the only pm installed by the dist), and ExtUtils::Manifest::manifind does not find it. XSLoader.pm is listed in the MANIFEST, but manifind does not use the MANIFEST file, and instead returns all the files File::Find::find sees in the dist.

I am using App-cpanminus-1.7034, and the install.json looks like
`{"pathname":"S/SA/SAPER/XSLoader-0.22.tar.gz","provides":{},"target":"XSLoader","version":"0.22","dist":"XSLoader-0.22","name":"XSLoader"}`

**Comment by miyagawa** [comment] 2016-08-14 21:38
Dupe of https://github.com/perl-carton/carton/issues/210 https://rt.perl.org/Public/Bug/Display.html?id=128836 https://github.com/miyagawa/cpanminus/pull/511

**Closed by miyagawa** 2016-08-14 21:38 UTC
